---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{.Values.nodeName}}
  namespace: {{.Release.Namespace}}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: "{{.Values.nodeName}}-role"
  namespace: {{.Release.Namespace}}
rules:
  - apiGroups:
      - certificates.k8s.io
    resources:
      - certificatesigningrequests
    verbs:
      - update
      - delete
      - create
      - get
      - list
      - watch
      - patch
  - apiGroups:
      - "apps"
    resources:
      - deployments
    verbs:
      - create
      - delete
      - list
      - get
      - update
      - patch
  - apiGroups:
      - "coordination.k8s.io"
    resources:
      - leases
    verbs:
      - update
      - create
      - get
      - list
      - watch
      - patch
  - apiGroups:
      - "networking.k8s.io"
    resources:
      - ingresses
    verbs:
      - update
      - create
      - get
      - list
      - watch
      - patch
      - delete
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  - apiGroups:
      - ""
    resources:
      - secrets
      - services
      - serviceaccounts
      - namespaces
    verbs:
      - get
      - list
      - watch
  # For https://kubernetes.io/docs/reference/kubernetes-api/
  # authentication-resources/token-request-v1/
  - apiGroups: [""]
    resources: ["serviceaccounts/token", "namespaces"]
    verbs:
      - create
      - get
      - list
  - apiGroups:
      - ""
    resources:
      - pods
      - services
    verbs:
      - update
      - create
      - get
      - list
      - watch
      - patch
      - delete
  - apiGroups:
      - ""
    resources:
      - nodes
    verbs:
      - create
      - get
      - delete
  - apiGroups:
      - ""
    resources:
      - nodes/status
    verbs:
      - update
      - patch
  - apiGroups:
      - ""
    resources:
      - pods/status
    verbs:
      - update
      - patch
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - create
      - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: "{{.Values.nodeName}}-rolebinding"
  namespace: {{.Release.Namespace}}
subjects:
  - kind: ServiceAccount
    name: {{.Values.nodeName}}
    namespace: {{.Release.Namespace}}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: "{{.Values.nodeName}}-role"
---
apiVersion: v1
kind: Secret
metadata:
  name: "{{.Values.nodeName}}-secret"
  namespace: "{{.Release.Namespace}}"
  annotations:
    kubernetes.io/service-account.name: {{.Values.nodeName}}
  labels:
    kubernetes.io/service-account.name: {{.Values.nodeName}}
type: kubernetes.io/service-account-token
